return {
  'hedyhli/outline.nvim',
  lazy = true,
  cmd = { 'Outline', 'OutlineOpen' },
  keys = {
    { '<leader>lo', '<cmd>OutlineOpen<CR>', desc = 'Outline [o]pen' },
    { '<leader>lr', '<cmd>OutlineRefresh<CR>', desc = 'Outline [r]efresh' },
  },
  opts = {
    outline_window = {
      hide_cursor = true,
      width = 40,
      relative_width = false,
    },
    outline_items = {
      auto_update_events = {
        follow = { 'CursorMoved' },
        items = { 'InsertLeave', 'BufWritePost' },
      },
    },
    keymaps = {
      close = {},
    },
    symbols = {
      icons = {
        File = { icon = '󰈔', hl = 'Identifier' },
        Module = { icon = '󰆧', hl = 'Include' },
        Namespace = { icon = '󰅪', hl = 'Include' },
        Package = { icon = '󰏗', hl = 'Include' },
        Class = { icon = '𝓒', hl = 'Type' },
        Method = { icon = '𝓶', hl = 'Function' },
        Property = { icon = '', hl = 'Identifier' },
        Field = { icon = '󰆨', hl = 'Identifier' },
        Constructor = { icon = '', hl = 'Special' },
        Enum = { icon = 'ℰ', hl = 'Type' },
        Interface = { icon = '𝐢', hl = 'Type' },
        Function = { icon = 'ƒ', hl = 'Function' },
        Variable = { icon = '', hl = 'Constant' },
        Constant = { icon = '', hl = 'Constant' },
        String = { icon = '𝓐', hl = 'String' },
        Number = { icon = '#', hl = 'Number' },
        Boolean = { icon = '⊨', hl = 'Boolean' },
        Array = { icon = '󰅪', hl = 'Constant' },
        Object = { icon = '⦿', hl = 'Type' },
        Key = { icon = '🔐', hl = 'Type' },
        Null = { icon = 'NULL', hl = 'Type' },
        EnumMember = { icon = '', hl = 'Identifier' },
        Struct = { icon = 'ѕ', hl = 'Structure' },
        Event = { icon = '🗲', hl = 'Type' },
        Operator = { icon = '+', hl = 'Identifier' },
        TypeParameter = { icon = '𝙏', hl = 'Identifier' },
        Component = { icon = '󰅴', hl = 'Function' },
        Fragment = { icon = '󰅴', hl = 'Constant' },
        TypeAlias = { icon = ' ', hl = 'Type' },
        Parameter = { icon = ' ', hl = 'Identifier' },
        StaticMethod = { icon = ' ', hl = 'Function' },
        Macro = { icon = ' ', hl = 'Function' },
      },
    },
  },
}
